---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: podinfo-dev
  chart:
    git: git@github.com:jantoebes/helm-operator-get-started
    path: charts/podinfo
    ref: cee80aa
  values:
    image: toebez/podinfo:dev-9689bbc7
    replicaCount: 1
    hpa:
      enabled: false
